---
title: "A4: Incarceration"
output: html_document
---

### Introduction

An introduction of the problem domain and a description of the variable(s) you are choosing to analyze (and why!)

### Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

These will likely be calculated using your DPLYR skills, answering questions such as: 

- What is the average value of my variable across all the counties (in the current year)?
- Where is my variable the highest / lowest?
- How much has my variable change over the last N years?

Feel free to calculate and report values that you find relevant. Again, remember that the purpose is to think about how these measure of incarceration vary by race.

### The Dataset

The incarceration data utilized in this analysis was compiled by the Vera Institute, a prominent nonprofit organization dedicated to criminal justice reform and research. The data collection process likely involved a combination of methods such as surveys, administrative records, and collaborations with various criminal justice agencies across the United States. The primary aim of this data collection effort was to comprehensively examine trends, disparities, and systemic issues within the U.S. criminal justice system, particularly concerning incarceration rates and their intersection with demographic factors such as race and socioeconomic status. With likely numerous observations representing diverse geographic regions, demographic profiles, and temporal snapshots, the dataset offers a rich source of information for understanding the complexities of incarceration in the United States. However, ethical considerations loom large in the analysis of such data. Questions regarding potential biases in data collection methods, power dynamics within the criminal justice system, and the ethical implications of research findings on affected communities must be carefully navigated. Furthermore, limitations such as sampling biases, incomplete data, and contextual factors affecting incarceration rates underscore the importance of critical scrutiny and cautious interpretation when working with this dataset.

### Trends Over Time Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The first chart that you will create and include will show the trend over time of your variable/topic. Think carefully about what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Show more than one, but fewer than ~10 trends
  - This may mean showing the same measure for different locations or different racial groups. Think carefully about a meaningful comparison of locations (e.g., the top 10 counties in a state, top 10 states, etc.)
- You must have clear x and y axis labels
- The chart needs a clear title 
- You need a legend for your different line colors and a clear legend title

When we say "clear" or "human readable" titles and labels, that means that you should not just display the variable name.

Here's an example of how to run an R script inside an RMarkdown file:

```{r, echo = FALSE, code = readLines("chart1_example.R")}
```

### Variable Comparison Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The second chart that you will create and include will show how two different (continuous) variables are related to one another. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- You must have clear x and y axis labels
- The chart needs a clear title 
- If you choose to add a color encoding (not required), you need a legend for your different color and a clear legend title

### Map

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The last chart that you will create and include will show how a variable is distributed geographically. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Your map needs a title
- Your color scale needs a legend with a clear label
- Use a map based coordinate system to set the aspect ratio of your map

